# Auto-generated by cve2grammar/generalizer — do not edit by hand.
# Generated: 2026-04-21T00:41:05Z
# Model: claude-sonnet-4-6
# Prompt version: 1
# Bugs: 42 (crash oracle)
# Source: cve2grammar generalize-candidates --oracle crash

# === check_constraint_between_self_ref (1 bug: MR-SQLITE-0151) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} {Type-Name}, CHECK({Col-Name} BETWEEN {Expr} AND {Expr}));\n"
    "INSERT INTO {Table-Name} VALUES ({Literal});\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr}",
    weight=3.0)

# === check_constraint_case_expr_type_coercion (1 bug: MR-SQLITE-0144) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} {Type-Name}, CHECK(CASE {Col-Name} WHEN {Expr} THEN {Literal} END));\n"
    "INSERT INTO {Table-Name} VALUES({Literal})",
    weight=3.0)

# === check_constraint_self_ref_col (1 bug: MR-SQLITE-0143) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} {Type-Name}, CHECK({Col-Name} IN ({Col-Name})));\n"
    "INSERT INTO {Table-Name} VALUES({Literal});\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr}",
    weight=3.0)

# === check_constraint_self_ref_in_expr (1 bug: MR-SQLITE-0140) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} CHECK({Col-Ref} IN({Col-Ref})), {Col-Name} {Type-Name});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES({Literal})",
    weight=3.0)

# === collate_binary_index_between (1 bug: MR-SQLITE-0141) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def});\n"
    "CREATE INDEX {Table-Name} ON {Table-Name}(({Expr}) COLLATE BINARY);\n"
    "SELECT {Result-Col-List} FROM {Table-Name} WHERE ({Expr}) COLLATE BINARY BETWEEN {Expr} AND {Expr}",
    weight=3.0)

# === create_virtual_table_rtree (1 bug: MR-SQLITE-0122) ===
ctx.rule("Sql-Stmt", "CREATE VIRTUAL TABLE {Table-Name} USING rtree", weight=3.0)

# === cross_join_in_subexpr_order_by (1 bug: MR-SQLITE-0022) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name} ({Col-Def-List}, PRIMARY KEY ({Col-Name-List}));\n"
    "CREATE TABLE {Table-Name} ({Col-Def});\n"
    "INSERT INTO {Table-Name} VALUES ({Literal});\n"
    "SELECT {Result-Col-List} FROM {Table-Name}, {Table-Name} WHERE ({Col-Ref} >= {Literal} OR {Col-Ref} < {Literal}) AND {Col-Ref} IN ({Literal}, {Col-Ref}) ORDER BY {Boundary-Int}",
    weight=3.0)

# === filter_clause_subquery_window_agg (1 bug: MR-SQLITE-0132) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name});\n"
    "CREATE TABLE {Table-Name}({Col-Name}, {Col-Name} UNIQUE);\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES(NULL);\n"
    "SELECT {Agg-Func}(*) FROM {Table-Name}, {Table-Name} WHERE (SELECT {Agg-Func}({Expr}) FILTER(WHERE {Col-Ref}))",
    weight=3.0)

# === fts5_encoding_cast_compare (1 bug: MR-SQLITE-0145) ===
ctx.rule("Sql-Stmt",
    "PRAGMA encoding = 'UTF16';\n"
    "CREATE VIRTUAL TABLE {Table-Name} USING fts5({Col-Name});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Blob-Literal});\n"
    "SELECT * FROM {Table-Name} WHERE CAST(SUBSTR({Col-Name}, {Boundary-Int}) AS TEXT) > {Expr}",
    weight=3.0)

# === fts5_integrity_check_porter_prefix (1 bug: MR-SQLITE-0153) ===
ctx.rule("Sql-Stmt",
    "CREATE VIRTUAL TABLE {Table-Name} USING fts5({Col-Name}, prefix = {Boundary-Int}, tokenize = \"porter ascii\", prefix = {Boundary-Int});\n"
    "BEGIN;\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Blob-Literal});\n"
    "INSERT INTO {Table-Name}({Table-Name}) VALUES('integrity-check')",
    weight=3.0)

# === fts5_left_join_view_group_by (1 bug: MR-SQLITE-0142) ===
ctx.rule("Sql-Stmt",
    "CREATE VIRTUAL TABLE {Table-Name} USING fts5({Col-Name});\n"
    "CREATE TABLE {Table-Name}({Col-Def-List});\n"
    "CREATE VIEW {Table-Name}({Col-Name}) AS SELECT {Expr} GROUP BY {Expr};\n"
    "SELECT {Result-Col-List} FROM {Table-Name}, {Table-Name} LEFT JOIN {Table-Name} ON {Table-Name}.{Col-Name} MATCH {Expr} WHERE {Expr}",
    weight=3.0)

# === fts5_maintenance_commands (1 bug: MR-SQLITE-0137) ===
ctx.rule("Sql-Stmt",
    "PRAGMA locking_mode = EXCLUSIVE;\n"
    "PRAGMA {Journal-Mode};\n"
    "CREATE VIRTUAL TABLE {Table-Name} USING fts5({Col-Name});\n"
    "INSERT INTO {Table-Name}({Table-Name}) VALUES('integrity-check');\n"
    "INSERT INTO {Table-Name}({Table-Name}, rank) VALUES('usermerge', {Boundary-Int})",
    weight=3.0)

# === fts_transaction_savepoint_stress (1 bug: MR-SQLITE-0155) ===
ctx.rule("Sql-Stmt",
    "CREATE VIRTUAL TABLE {Table-Name} USING fts5({Col-Name});\n"
    "CREATE VIRTUAL TABLE {Table-Name} USING fts4({Col-Name});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES({Literal});\n"
    "BEGIN;\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr};\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Literal}), ({Literal});\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr};\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Literal});\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr};\n"
    "INSERT INTO {Table-Name}({Table-Name}) VALUES({Str-Literal});\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr};\n"
    "DROP TABLE {Table-Name}",
    weight=3.0)

# === generated_col_check_update_segfault (1 bug: MR-SQLITE-0111) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def}, {Col-Name} AS({GenCol-Expr}) {Gen-Storage}, {Col-Name} AS({GenCol-Expr}) CHECK({Expr}));\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr}",
    weight=3.0)

# === generated_col_fk_self_ref_type_affinity (1 bug: MR-SQLITE-0164) ===
ctx.rule("Sql-Stmt",
    "PRAGMA foreign_keys = {Pragma-Bool};\n"
    "CREATE TABLE {Table-Name}({Col-Name} {Type-Name} AS ({GenCol-Expr}) UNIQUE, {Col-Name} {Type-Name} UNIQUE, FOREIGN KEY({Col-Name}) REFERENCES {Table-Name}({Col-Name}));\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Literal}), ({Literal})",
    weight=3.0)

# === generated_col_fk_update_segfault (1 bug: MR-SQLITE-0102) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def-List}, PRIMARY KEY({Col-Name}) FOREIGN KEY({Col-Name}) REFERENCES {Table-Name});\n"
    "CREATE VIRTUAL TABLE {Table-Name} USING fts4;\n"
    "CREATE INDEX {Table-Name} ON {Table-Name}({Expr}, {Expr}, {Expr});\n"
    "INSERT INTO {Table-Name} VALUES ({Literal}), ({Literal});\n"
    "PRAGMA foreign_keys = true;\n"
    "ANALYZE;\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr}",
    weight=3.0)

# === generated_col_foreign_key_segfault (1 bug: MR-SQLITE-0123) ===
ctx.rule("Sql-Stmt",
    "PRAGMA foreign_keys = {Pragma-Bool};\n"
    "CREATE TEMP TABLE {Table-Name}({Col-Def-List}, {Col-Name} {Type-Name} GENERATED ALWAYS AS ({GenCol-Expr}) {Gen-Storage}, FOREIGN KEY({Col-Name}) REFERENCES {Table-Name}({Col-Name}) ON DELETE CASCADE);\n"
    "CREATE UNIQUE INDEX {Col-Name} ON {Table-Name}({Expr}, {Expr}, {Expr});\n"
    "CREATE UNIQUE INDEX {Col-Name} ON {Table-Name}({Expr}, {Expr}, {Col-Ref});\n"
    "CREATE INDEX {Col-Name} ON {Table-Name}({Expr}, {Expr}, {Col-Ref});\n"
    "VACUUM;\n"
    "INSERT OR REPLACE INTO {Table-Name}({Col-Name-List}) VALUES ({Literal}, {Literal}), ({Literal}, {Literal})",
    weight=3.0)

# === generated_col_insert_integrity (1 bug: MR-SQLITE-0110) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def-List});\n"
    "PRAGMA integrity_check;\n"
    "INSERT INTO {Table-Name} VALUES ({Expr-List}), ({Expr-List})",
    weight=3.0)

# === generated_col_not_null_replace (1 bug: MR-SQLITE-0108) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} NOT NULL AS({GenCol-Expr}) {Gen-Storage}, {Col-Name} {Type-Name});\n"
    "REPLACE INTO {Table-Name}({Col-Name}) VALUES(NULL)",
    weight=3.0)

# === generated_col_not_null_replace_null (1 bug: MR-SQLITE-0161) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def-List}, {Col-Name} AS({GenCol-Expr}) NOT NULL);\n"
    "REPLACE INTO {Table-Name}({Col-Name}) VALUES(NULL)",
    weight=3.0)

# === generated_col_primary_key_unique (1 bug: MR-SQLITE-0097) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} INTEGER PRIMARY KEY GENERATED ALWAYS AS ({GenCol-Expr}) {Gen-Storage}, {Col-Name} UNIQUE GENERATED ALWAYS AS ({GenCol-Expr}) {Gen-Storage}, {Col-Name} {Type-Name} UNIQUE);\n"
    "INSERT INTO {Table-Name} VALUES(NULL)",
    weight=3.0)

# === generated_col_unique_replace_null (1 bug: MR-SQLITE-0163) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def-List}, {Col-Name} AS({GenCol-Expr}) UNIQUE);\n"
    "REPLACE INTO {Table-Name} VALUES({Literal})",
    weight=3.0)

# === generated_col_unique_update_btree (1 bug: MR-SQLITE-0157) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} UNIQUE AS({GenCol-Expr}), {Col-Name}, {Col-Name});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES({Literal});\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr}, {Col-Name} = {Expr} WHERE ({Col-Ref}) >= {Literal}",
    weight=3.0)

# === index_expr_like_coalesce_utf16 (1 bug: MR-SQLITE-0146) ===
ctx.rule("Sql-Stmt",
    "PRAGMA encoding = 'UTF16';\n"
    "CREATE TABLE {Table-Name}({Col-Name} {Type-Name});\n"
    "CREATE INDEX {Col-Name} ON {Table-Name}({Expr} LIKE COALESCE({Col-Ref}, {Literal}));\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Literal}), ({Literal})",
    weight=3.0)

# === left_join_between_comparison_assert (1 bug: MR-SQLITE-0148) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def-List});\n"
    "CREATE TABLE {Table-Name}({Col-Def-List});\n"
    "SELECT {Result-Col-List} FROM {Table-Name} LEFT JOIN {Table-Name} WHERE ({Col-Ref} BETWEEN {Expr} AND {Expr}) > ({Expr} AND {Expr})",
    weight=3.0)

# === locking_mode_journal_mode_transition (1 bug: MR-SQLITE-0159) ===
ctx.rule("Sql-Stmt",
    "PRAGMA locking_mode = EXCLUSIVE;\n"
    "PRAGMA journal_mode = {Journal-Mode};\n"
    "PRAGMA locking_mode = NORMAL;\n"
    "PRAGMA integrity_check;\n"
    "PRAGMA journal_mode = {Journal-Mode}",
    weight=3.0)

# === partial_index_utf16_update_conflict (1 bug: MR-SQLITE-0136) ===
ctx.rule("Sql-Stmt",
    "PRAGMA encoding = 'UTF16';\n"
    "CREATE TABLE {Table-Name}({Col-Name} {Type-Name}, {Col-Name});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Str-Literal}), ({Literal});\n"
    "CREATE INDEX {Table-Name} ON {Table-Name}({Col-Name}) WHERE {Col-Ref} GLOB {Expr};\n"
    "UPDATE {Table-Name} SET {Col-Name}={Literal}",
    weight=3.0)

# === reindex_generated_col_fts4 (1 bug: MR-SQLITE-0129) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def-List});\n"
    "CREATE VIRTUAL TABLE {Table-Name} USING fts4;\n"
    "INSERT INTO {Table-Name} VALUES({Expr});\n"
    "{Reindex-Stmt}",
    weight=3.0)

# === replace_after_delete_trigger_recursive (1 bug: MR-SQLITE-0093) ===
ctx.rule("Sql-Stmt",
    "PRAGMA recursive_triggers = {Pragma-Bool};\n"
    "CREATE TABLE {Table-Name}({Col-Def-List});\n"
    "CREATE UNIQUE INDEX {Table-Name} ON {Table-Name}({Col-Name}) WHERE {Expr};\n"
    "CREATE TRIGGER {Table-Name} AFTER DELETE ON {Table-Name} BEGIN DELETE FROM {Table-Name}; END;\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES({Literal});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES({Literal}), ({Literal});\n"
    "REPLACE INTO {Table-Name}({Col-Name-List}) VALUES({Expr-List})",
    weight=3.0)

# === replace_gencol_fk_fts (1 bug: MR-SQLITE-0103) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name} ({Col-Def-List}, FOREIGN KEY({Col-Name}) REFERENCES {Table-Name}({Col-Name}));\n"
    "CREATE VIRTUAL TABLE {Table-Name} USING fts4({Col-Name});\n"
    "PRAGMA foreign_keys = true;\n"
    "INSERT INTO {Table-Name} VALUES ({Expr});\n"
    "REPLACE INTO {Table-Name}({Col-Name-List}) VALUES ({Expr-List}), ({Expr-List})",
    weight=3.0)

# === row_value_check_upsert_conflict (1 bug: MR-SQLITE-0167) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} CHECK(((0, 0) > (0, {Col-Ref}))));\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES({Literal}) ON CONFLICT({Col-Name}) DO UPDATE SET {Col-Name} = {Expr}",
    weight=3.0)

# === row_value_in_subquery_with_window_func (1 bug: MR-SQLITE-0162) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def-List});\n"
    "SELECT ({Expr}, {Expr}) IN(SELECT {Agg-Func}, {Win-Func-Expr} OVER({Over-Clause})) FROM {Table-Name}",
    weight=3.0)

# === rtree_left_join_segfault (1 bug: MR-SQLITE-0126) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} {Type-Name});\n"
    "CREATE VIRTUAL TABLE {Table-Name} USING rtree({Col-Name}, {Col-Name}, {Col-Name});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES({Literal});\n"
    "SELECT {Result-Col-List} FROM {Table-Name} LEFT JOIN {Table-Name} ON {Expr} WHERE {Expr}",
    weight=3.0)

# === rtree_row_value_window_affinity (1 bug: MR-SQLITE-0156) ===
ctx.rule("Sql-Stmt",
    "CREATE VIRTUAL TABLE {Table-Name} USING rtree({Col-Name}, {Col-Name}, {Col-Name});\n"
    "SELECT * FROM {Table-Name} WHERE (({Expr}, {Expr}) IN (SELECT {Agg-Func}(*), {Win-Func-Expr} FROM {Table-Name}), {Expr}) <= ({Col-Ref}, {Expr})",
    weight=3.0)

# === rtree_virtual_table_join_corrupt (1 bug: MR-SQLITE-0149) ===
ctx.rule("Sql-Stmt",
    "CREATE VIRTUAL TABLE {Table-Name} USING rtree({Col-Name}, {Col-Name}, {Col-Name});\n"
    "CREATE TABLE {Table-Name}({Col-Name});\n"
    "INSERT INTO {Table-Name} VALUES ({Literal}), ({Literal});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Literal}), ({Literal});\n"
    "CREATE VIEW {Table-Name} AS {Select-Stmt};\n"
    "SELECT {Result-Col-List} FROM {Table-Name} LEFT JOIN {Table-Name} INNER JOIN {Table-Name}",
    weight=3.0)

# === self_ref_fk_check_cast_replace (1 bug: MR-SQLITE-0168) ===
ctx.rule("Sql-Stmt",
    "PRAGMA foreign_keys = {Pragma-Bool};\n"
    "CREATE TABLE {Table-Name}({Col-Name} TEXT PRIMARY KEY, {Col-Name} INT UNIQUE REFERENCES {Table-Name} CHECK(CAST({Col-Ref} AS INT) BETWEEN {Boundary-Int} AND CASE WHEN {Expr} THEN {Col-Ref} END));\n"
    "REPLACE INTO {Table-Name}({Col-Name}, {Col-Name}) VALUES({Float-Literal}, {Boundary-Int}), ({Boundary-Int}, {Blob-Literal})",
    weight=3.0)

# === window_func_in_exists_subquery (1 bug: MR-SQLITE-0055) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} {Type-Name});\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Literal});\n"
    "SELECT * FROM {Table-Name} WHERE EXISTS (SELECT {Win-Func-Expr}, {Win-Func-Expr} FROM {Table-Name}) BETWEEN {Literal} AND {Literal}",
    weight=3.0)

# === window_func_in_subquery_ntile (1 bug: MR-SQLITE-0147) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} UNIQUE);\n"
    "SELECT * FROM {Table-Name} WHERE ({Col-Ref}, {Expr}) IN(SELECT {Win-Func-Expr}, {Literal} FROM {Table-Name})",
    weight=3.0)

# === window_func_in_subquery_row_value (1 bug: MR-SQLITE-0138) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} UNIQUE);\n"
    "INSERT INTO {Table-Name} VALUES({Literal});\n"
    "SELECT * FROM {Table-Name} WHERE ({Expr}, {Col-Ref}) IN(SELECT {Win-Func-Expr}, {Win-Func-Expr} FROM {Table-Name})",
    weight=3.0)

# === window_func_in_subquery_where (1 bug: MR-SQLITE-0139) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Name} UNIQUE);\n"
    "SELECT * FROM {Table-Name} WHERE ({Col-Name}, {Literal}) IN (SELECT {Win-Func-Expr} OVER({Over-Clause}), {Literal})",
    weight=3.0)

# === without_rowid_generated_col_update (1 bug: MR-SQLITE-0098) ===
ctx.rule("Sql-Stmt",
    "PRAGMA temp_store = MEMORY;\n"
    "CREATE TEMP TABLE {Table-Name}({Col-Name}, {Col-Name} AS({GenCol-Expr}) CHECK(NULL) UNIQUE NOT NULL, {Col-Name} CHECK({Expr}) PRIMARY KEY) WITHOUT ROWID;\n"
    "CREATE UNIQUE INDEX {Table-Name} ON {Table-Name}(CAST({Expr} AS INT)) WHERE {Expr};\n"
    "REINDEX;\n"
    "INSERT INTO {Table-Name}({Col-Name}) VALUES ({Literal}), ({Literal});\n"
    "REPLACE INTO {Table-Name}({Col-Name}, {Col-Name}) VALUES ({Literal}, {Literal}), ({Blob-Literal}, NULL);\n"
    "UPDATE {Table-Name} SET {Col-Name} = {Expr}",
    weight=3.0)

# === without_rowid_upsert_conflict (1 bug: MR-SQLITE-0158) ===
ctx.rule("Sql-Stmt",
    "CREATE TABLE {Table-Name}({Col-Def-List}) WITHOUT ROWID;\n"
    "INSERT OR FAIL INTO {Table-Name}({Col-Name-List}) VALUES ({Expr-List}) ON CONFLICT({Col-Name}) DO UPDATE SET {Col-Name} = {Expr}",
    weight=3.0)

